### ISSUE TITLE
Plans to update to streams?

### ISSUE THREAD

**Issue by flintinatux** [jimf/prop-factory#1]
The rewrite of `mithril.js` will upgrade the functionality of `m.prop`'s to be [streams of reactive data](https://github.com/lhorie/mithril.js/blob/rewrite/docs/prop.md), rather than just getter/setter functions.  Curious if there were plans to do something similar here?

**Comment by jimf** [comment]
Hi Scott. That's cool, and seems like a compelling change. I haven't been keeping up with Mithril admittedly. I have no plans of making this an observable streams lib, but if you're looking for some, the following are on my radar:
- [RxJS](http://reactivex.io/)
- [Bacon.js](https://baconjs.github.io/)
- [most.js](https://github.com/cujojs/most)
- [Highland.js](http://highlandjs.org/)
- [flyd](https://github.com/paldepind/flyd)

**Comment by flintinatux** [comment]
Awesome, thanks for the list!
